/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_darkprograms_mysqldecrypter_util_HashUtil */

#ifndef _Included_com_darkprograms_mysqldecrypter_util_HashUtil
#define _Included_com_darkprograms_mysqldecrypter_util_HashUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_darkprograms_mysqldecrypter_util_HashUtil
 * Method:    getHash
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jintArray JNICALL Java_com_darkprograms_mysqldecrypter_util_HashUtil_getHash
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif